export default {
  index: 'Overview',
  avatar: 'Avatar',
  badge: 'Badge',
  button: 'Button',
  card: 'Card',
  checkbox: 'Checkbox',
  input: 'Input',
  modal: 'Modal',
  select: 'Select',
  spinner: 'Spinner',
  textarea: 'Textarea',
  toast: 'Toast',
  tooltip: 'Tooltip',
}
